# Generated by Django 4.0 on 2022-01-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0003_remove_koszyk_data_zamowienia'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='koszyk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='koszyk.koszyk'),
        ),
    ]
