# Generated by Django 4.0 on 2022-01-08 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profil_koszyk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='koszyk',
        ),
    ]
