# Generated by Django 4.0 on 2022-01-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0022_remove_order_adres'),
        ('users', '0003_remove_profil_koszyk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='koszyk.adres'),
        ),
    ]
