# Generated by Django 4.0 on 2022-01-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profil_adres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adres',
        ),
    ]
