# Generated by Django 4.0 on 2022-01-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0026_remove_adres_user'),
        ('users', '0005_remove_profil_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adres',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='koszyk.adres'),
        ),
    ]
