# Generated by Django 4.0 on 2022-01-07 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witryna', '0005_remove_cartitem_koszyk_remove_cartitem_produkt_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('koszyk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=1)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witryna.produkt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='KoszykPrzedmiot',
        ),
        migrations.AddField(
            model_name='koszyk',
            name='przedmioty',
            field=models.ManyToManyField(to='koszyk.OrderItem'),
        ),
    ]
