# Generated by Django 4.0 on 2022-01-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0002_orderitem_delete_koszykprzedmiot_koszyk_przedmioty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koszyk',
            name='data_zamowienia',
        ),
    ]
