# Generated by Django 4.0 on 2022-01-07 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0003_remove_koszyk_data_zamowienia'),
    ]

    operations = [
        migrations.AddField(
            model_name='koszyk',
            name='data_zamowienia',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
