# Generated by Django 4.0 on 2022-01-07 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0004_koszyk_data_zamowienia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koszyk',
            name='data_zamowienia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
