# Generated by Django 4.0 on 2022-01-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0005_alter_koszyk_data_zamowienia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
