# Generated by Django 4.0 on 2022-01-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0008_alter_cart_user_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koszyk.cartitem'),
        ),
    ]
