# Generated by Django 4.0 on 2022-01-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0009_alter_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
