# Generated by Django 4.0 on 2022-01-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0010_remove_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='koszyk.CartItem'),
        ),
    ]
