# Generated by Django 4.0 on 2022-01-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0011_remove_cart_product_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
    ]
