# Generated by Django 4.0 on 2022-01-08 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0014_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
