# Generated by Django 4.0 on 2022-01-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0015_remove_cartitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
