# Generated by Django 4.0 on 2022-01-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0016_rename_products_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.CharField(default='test', max_length=111),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
