# Generated by Django 4.0 on 2022-01-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0017_cart_quantity_alter_cart_product_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
