# Generated by Django 4.0 on 2022-01-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0019_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
