# Generated by Django 4.0 on 2022-01-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profil_adres'),
        ('koszyk', '0024_alter_adres_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profil'),
        ),
    ]
