# Generated by Django 4.0 on 2022-01-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0025_alter_adres_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adres',
            name='user',
        ),
    ]
