# Generated by Django 4.0 on 2022-01-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adres_alter_profil_adres'),
        ('koszyk', '0026_remove_adres_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adres',
        ),
    ]
