# Generated by Django 4.0 on 2022-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witryna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='produkt_zdjecia'),
        ),
    ]
