# Generated by Django 4.0 on 2022-01-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witryna', '0002_alter_produkt_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='img',
            new_name='image',
        ),
    ]
