# Generated by Django 4.0 on 2022-01-07 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('witryna', '0003_rename_img_produkt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='produkt',
            name='dostepny',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='ilosc',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=1)),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witryna.cart')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='witryna.produkt')),
            ],
        ),
    ]
