# Generated by Django 4.0 on 2022-01-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('witryna', '0004_cart_produkt_dostepny_produkt_ilosc_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='koszyk',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='produkt',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
